# Generated by Django 6.0.5 on 2026-05-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('clone_path', models.CharField(blank=True, max_length=512)),
                ('last_synced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'repositories',
                'ordering': ['-last_analyzed_at'],
            },
        ),
    ]
