# Generated by Django 6.0.5 on 2026-05-15 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['-last_analyzed_at', '-id'], 'verbose_name_plural': 'repositories'},
        ),
    ]
