# Generated by Django 6.0.5 on 2026-05-14 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('termination_reason', models.CharField(blank=True, choices=[('completed', 'Completed'), ('max_iterations', 'Max Iterations'), ('max_tokens', 'Max Tokens'), ('timeout', 'Timeout'), ('duplicate_calls', 'Duplicate Calls'), ('error', 'Error')], max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('llm_provider', models.CharField(max_length=50)),
                ('llm_model', models.CharField(max_length=100)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('iteration_count', models.IntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='repos.repository')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['repository', 'status'], name='research_re_reposit_b52622_idx'), models.Index(fields=['repository', '-created_at'], name='research_re_reposit_2856d1_idx')],
            },
        ),
    ]
