# Generated by Django 6.0.5 on 2026-05-14 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(db_index=True, max_length=512)),
                ('line_start', models.IntegerField(blank=True, null=True)),
                ('line_end', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='research.researchsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
