# Generated by Django 6.0.5 on 2026-05-14 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_finding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('tool_name', models.CharField(db_index=True, max_length=100)),
                ('arguments', models.JSONField()),
                ('result_content', models.TextField()),
                ('result_truncated', models.BooleanField(default=False)),
                ('is_error', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='research.researchsession')),
            ],
            options={
                'ordering': ['session', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('session', 'sequence'), name='unique_toolcall_sequence_per_session')],
            },
        ),
    ]
